[theme]
primaryColor = "#00FFA3"
backgroundColor = "#0F0F12"
secondaryBackgroundColor = "#1E1E24"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false